# Generated by Django 5.0.3 on 2024-03-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_image',
            new_name='docs_image',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doc_spec',
        ),
        migrations.AddField(
            model_name='doctors',
            name='docs_name',
            field=models.CharField(default='SomeDefaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='doctors',
            name='docs_spec',
            field=models.CharField(default='SomeDefaultValue', max_length=100),
        ),
    ]
